import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Clipboard, LogOut, Mail, Search, ShieldAlert, Upload } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { normalizeProspect, parseProspectJson, type ProspectImport } from "@/lib/prospect-import";

export const Route = createFileRoute("/admin")({ head:()=>({meta:[{title:"Dental AI Sales CRM"}]}), component:Admin });
type Tab="prospects"|"research"|"import"|"campaigns"|"queue";
type Prospect={id:string;practice_name:string;city:string|null;state:string|null;stage:string;source:string;opportunity_score:number|null;email:string|null;website:string|null};
type Counts={prospects:number;qualified:number;replied:number;demos:number;queued:number;sent:number;suppressed:number};
const tabs:[Tab,string][]=[["prospects","Prospects"],["research","AI Research"],["import","Import"],["campaigns","Campaigns"],["queue","Email Queue"]];
const db=()=>supabase as any;

function buildResearchPrompt(city:string,state:string,count:string){return `Find up to ${count||"25"} independent dental practices in ${city||"the selected city"}${state?`, ${state}`:""} that could be prospects for an AI front desk and website improvement service.\n\nReturn ONLY a JSON array. Do not add markdown or commentary. Do not invent missing information. Use null when not verified. Each object must use these keys:\npractice_name, website, domain, phone, email, address, city, state, postal_code, google_rating, google_reviews, contact_name, contact_title, source_url, notes.\n\nPrefer independent/local practices rather than large national chains. Preserve a source URL for verification. If a field is inferred rather than directly supported, leave it null.`}

function Admin(){
 const[authorized,setAuthorized]=useState<boolean|null>(null),[tab,setTab]=useState<Tab>("prospects"),[city,setCity]=useState(""),[state,setState]=useState(""),[count,setCount]=useState("25"),[paste,setPaste]=useState(""),[message,setMessage]=useState(""),[prospects,setProspects]=useState<Prospect[]>([]),[loading,setLoading]=useState(true),[counts,setCounts]=useState<Counts>({prospects:0,qualified:0,replied:0,demos:0,queued:0,sent:0,suppressed:0}),[outbound,setOutbound]=useState(false),[researchSource,setResearchSource]=useState("chatgpt");
 const prompt=useMemo(()=>buildResearchPrompt(city,state,count),[city,state,count]);
 async function refresh(){setLoading(true);const[{data:p,error},{data:q},{data:s},{data:settings}]=await Promise.all([db().from("prospects").select("id,practice_name,city,state,stage,source,opportunity_score,email,website").order("created_at",{ascending:false}).limit(250),db().from("email_queue").select("status"),db().from("suppressions").select("id"),db().from("outbound_settings").select("outbound_enabled").eq("singleton",true).maybeSingle()]);if(error)setMessage(`Database: ${error.message}`);const rows=(p||[]) as Prospect[];setProspects(rows);const queue=q||[];setCounts({prospects:rows.length,qualified:rows.filter(x=>x.stage==="qualified").length,replied:rows.filter(x=>x.stage==="replied").length,demos:rows.filter(x=>x.stage==="demo").length,queued:queue.filter((x:any)=>x.status==="queued").length,sent:queue.filter((x:any)=>x.status==="sent").length,suppressed:(s||[]).length});setOutbound(Boolean(settings?.outbound_enabled));setLoading(false)}
 useEffect(()=>{void (async()=>{const{data}=await supabase.auth.getSession();const user=data.session?.user;if(!user){window.location.replace("/admin/login");return}const{data:membership}=await db().from("platform_admins").select("user_id").eq("user_id",user.id).maybeSingle();if(!membership){await supabase.auth.signOut();window.location.replace("/admin/login");return}setAuthorized(true);await refresh()})()},[]);
 async function logout(){await supabase.auth.signOut();window.location.replace("/admin/login")}
 async function copyPrompt(provider:string){
   const source=provider.toLowerCase()==="perplexity"?"perplexity":"chatgpt";
   setResearchSource(source);
   try{
     if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(prompt)}
     else throw new Error("Clipboard API unavailable");
     setMessage(`${provider} research prompt copied.`);
   }catch{
     const textarea=document.createElement("textarea");
     textarea.value=prompt;
     textarea.setAttribute("readonly","");
     textarea.style.position="fixed";
     textarea.style.opacity="0";
     document.body.appendChild(textarea);
     textarea.select();
     const ok=document.execCommand("copy");
     document.body.removeChild(textarea);
     setMessage(ok?`${provider} research prompt copied.`:`Could not copy automatically. Select the prompt text and copy it manually.`);
   }
 }
 async function importPasted(){try{const parsed=parseProspectJson(paste);const source=tab==="research"?researchSource:"manual";const rows=parsed.map((x:ProspectImport)=>{const n=normalizeProspect(x);return{...n,source,verification_status:"unverified",stage:"new"}});if(!rows.length){setMessage("No valid prospect records found.");return}const{error}=await db().from("prospects").upsert(rows,{onConflict:"domain",ignoreDuplicates:true});if(error)throw error;await db().from("import_batches").insert({source,label:`Admin ${tab} import`,raw_payload:parsed,total_rows:parsed.length,new_rows:rows.length});setMessage(`${rows.length} valid records processed from ${source}. Existing domains were skipped.`);setPaste("");await refresh()}catch(e:any){setMessage(e?.message||"Could not import. Paste the JSON array returned by ChatGPT or Perplexity.")}}
 async function setStage(id:string,stage:string){const{error}=await db().from("prospects").update({stage,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMessage(error.message);else await refresh()}
 async function toggleOutbound(){const next=!outbound;const{error}=await db().from("outbound_settings").update({outbound_enabled:next,updated_at:new Date().toISOString()}).eq("singleton",true);if(error)setMessage(error.message);else{setOutbound(next);setMessage(next?"Outbound flag enabled. No sender worker is connected yet.":"All outbound disabled.")}}
 if(authorized!==true)return <main className="grid min-h-screen place-items-center bg-[#f4f7f6] text-[#123f3b]"><div className="rounded-2xl bg-white px-6 py-5 shadow-sm">Checking administrator access…</div></main>;
 return <main className="min-h-screen bg-[#f4f7f6] text-[#123f3b]"><header className="border-b bg-white"><div className="mx-auto flex min-h-20 max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-4"><div><strong className="text-lg">Dental AI · Platform Admin</strong><small className="block text-[#607772]">Sales CRM · Lovable database</small></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${outbound?"bg-red-50 text-red-700":"bg-amber-50 text-amber-800"}`}>Outbound {outbound?"ON":"OFF"}</span><Link to="/for-dentists" className="text-sm font-semibold text-[#1686d9]">Sales demo</Link><button onClick={()=>void logout()} className="inline-flex items-center gap-1.5 text-sm font-semibold text-[#607772]"><LogOut className="size-4"/>Sign out</button></div></div></header><section className="mx-auto max-w-7xl px-5 py-8"><nav className="mb-7 flex gap-2 overflow-x-auto">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-semibold ${tab===id?"bg-[#123f3b] text-white":"bg-white text-[#45635f]"}`}>{label}</button>)}</nav>{message&&<div role="status" className="mb-5 rounded-xl border bg-white px-4 py-3 text-sm">{message}</div>}{tab==="prospects"&&<Prospects rows={prospects} counts={counts} loading={loading} setStage={setStage}/>} {tab==="research"&&<Research city={city} state={state} count={count} paste={paste} setCity={setCity} setState={setState} setCount={setCount} setPaste={setPaste} copyPrompt={copyPrompt} importPasted={importPasted} researchSource={researchSource}/>} {tab==="import"&&<ImportPanel paste={paste} setPaste={setPaste} importPasted={importPasted}/>} {tab==="campaigns"&&<Campaigns/>} {tab==="queue"&&<Queue counts={counts} outbound={outbound} toggle={toggleOutbound}/>}</section></main>}

function Prospects({rows,counts,loading,setStage}:{rows:Prospect[];counts:Counts;loading:boolean;setStage:(id:string,s:string)=>void}){return <><div className="grid gap-4 sm:grid-cols-4">{[["Prospects",counts.prospects],["Qualified",counts.qualified],["Replied",counts.replied],["Demos",counts.demos]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-white p-5"><small className="text-[#607772]">{a}</small><strong className="mt-1 block text-3xl">{b}</strong></div>)}</div><div className="mt-6 overflow-hidden rounded-2xl bg-white"><div className="border-b p-5"><h2 className="font-bold">Prospect pipeline</h2><p className="text-sm text-[#607772]">New → Researching → Qualified → Email Queue → Contacted → Replied → Demo → Proposal → Won/Lost</p></div>{loading?<div className="p-10 text-center">Loading…</div>:rows.length===0?<div className="p-10 text-center"><Search className="mx-auto mb-3 text-[#8aa09c]"/><strong>No prospects yet</strong><p className="mt-1 text-sm text-[#607772]">Use AI Research or Import to add the first practices.</p></div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f4f7f6] text-xs uppercase text-[#607772]"><tr><th className="p-3">Practice</th><th>Location</th><th>Email</th><th>Source</th><th>Score</th><th className="pr-3">Stage</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-semibold">{x.practice_name}</td><td>{[x.city,x.state].filter(Boolean).join(", ")||"—"}</td><td>{x.email||"—"}</td><td>{x.source}</td><td>{x.opportunity_score??"—"}</td><td className="pr-3"><select value={x.stage} onChange={e=>void setStage(x.id,e.target.value)} className="rounded-lg border px-2 py-1">{["new","researching","qualified","email_queue","contacted","replied","demo","proposal","won","lost"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>}</div></>}
function Research(p:any){return <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">1. Create research prompt</h2><p className="mt-1 text-sm text-[#607772]">No API. Copy into ChatGPT or Perplexity. Selected source: <strong>{p.researchSource}</strong></p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="City" value={p.city} set={p.setCity} placeholder="Tampa"/><Field label="State" value={p.state} set={p.setState} placeholder="Florida"/><Field label="How many" value={p.count} set={p.setCount} placeholder="25"/></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>p.copyPrompt("ChatGPT")} className="rounded-xl bg-[#123f3b] px-4 py-3 text-sm font-semibold text-white"><Clipboard className="mr-2 inline h-4 w-4"/>Copy ChatGPT Prompt</button><button onClick={()=>p.copyPrompt("Perplexity")} className="rounded-xl border px-4 py-3 text-sm font-semibold"><Clipboard className="mr-2 inline h-4 w-4"/>Copy Perplexity Prompt</button></div></div><PasteBox paste={p.paste} setPaste={p.setPaste} action={p.importPasted} label="Import to CRM"/></div>}
function ImportPanel({paste,setPaste,importPasted}:any){return <div className="rounded-2xl bg-white p-6"><Upload className="mb-3"/><h2 className="text-xl font-bold">Import prospects</h2><p className="mt-1 text-sm text-[#607772]">Paste standard JSON from local scripts, Google Maps exports or another approved source. CSV upload comes next.</p><PasteBox paste={paste} setPaste={setPaste} action={importPasted} label="Import JSON"/></div>}
function PasteBox({paste,setPaste,action,label}:any){return <div className="mt-5 rounded-2xl bg-white"><textarea value={paste} onChange={e=>setPaste(e.target.value)} className="min-h-64 w-full rounded-xl border p-4 font-mono text-xs" placeholder='[{"practice_name":"..."}]'/><button onClick={()=>void action()} className="mt-3 rounded-xl bg-[#1686d9] px-4 py-3 text-sm font-semibold text-white">{label}</button></div>}
function Campaigns(){return <div className="rounded-2xl bg-white p-6"><Mail className="mb-3"/><h2 className="text-xl font-bold">Campaigns</h2><p className="mt-1 text-sm text-[#607772]">Database tables are active. Campaign creation/recipient staging is the next connection.</p></div>}
function Queue({counts,outbound,toggle}:{counts:Counts;outbound:boolean;toggle:()=>void}){return <div className="rounded-2xl bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><ShieldAlert className="mb-3"/><h2 className="text-xl font-bold">Email Queue Safety</h2><p className="mt-1 text-sm text-[#607772]">Minimum spacing: 60 seconds · suppression checked · duplicate recipient blocked.</p></div><button onClick={toggle} className={`rounded-xl px-4 py-3 text-sm font-bold ${outbound?"bg-red-600 text-white":"bg-[#123f3b] text-white"}`}>{outbound?"STOP ALL OUTBOUND":"Enable outbound flag"}</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Queued",counts.queued],["Sent",counts.sent],["Suppressed",counts.suppressed]].map(([a,b])=><div key={String(a)} className="rounded-xl bg-[#f4f7f6] p-4"><small>{a}</small><strong className="block text-2xl">{b}</strong></div>)}</div><p className="mt-5 text-xs text-[#607772]">No sender worker/provider is connected yet. Enabling the flag alone cannot send mail.</p></div>}
function Field({label,value,set,placeholder}:any){return <label className="text-sm font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="mt-1 block w-full rounded-xl border px-3 py-2 font-normal"/></label>}
