import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, Phone, MessageCircle, Sparkles, HeartHandshake, ShieldCheck, Star, ArrowRight } from "lucide-react";

export const Route = createFileRoute("/concierge")({ component: Concierge });

const hero="https://lh3.googleusercontent.com/aida-public/AB6AXuA0iEVLLRDQ84qokAVdYeqg0Hai9CwXY66T1ZF-3aLCxhCbHiv9PEeaTEM5BsVISk--APEqGrxjdBdB7DS6Ak4pwHW3tmuKSjiTtVKYro7cVkpcwsl8iIvnlUzklynRpYdXw-LyoYrPqmdR7Pm4-oYVh2FRY3kMasqHq2IB2T24ygY6wRnywN1IgioPNFhO9cBUn_Yt2rVU0BW9rQGlM6BwUSKYALNmcLfYszaSol513qJ-uDNRHb70";
const services=["Cosmetic Dentistry","Dental Implants","Family Dentistry","Invisalign®","Teeth Whitening","Emergency Care"];
function Brand(){return <a href="/designs" className="flex items-center gap-3"><span className="text-3xl text-[#c49a45]">✦</span><span className="font-display text-2xl tracking-[.12em] text-[#0b2347]">LaBelle <b className="font-sans text-sm font-medium tracking-[.22em] text-[#b88a35]">DENTAL</b></span></a>}
function Concierge(){return <main className="min-h-screen bg-white text-[#0b2347]">
<header className="sticky top-0 z-50 border-b border-[#eee7da] bg-white/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Brand/><nav className="hidden gap-7 text-xs font-bold md:flex"><a href="#care">About Us</a><a href="#services">Services</a><a href="#care">For Patients</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></nav><div className="flex items-center gap-3"><a className="hidden text-sm font-bold lg:block" href="tel:+855236767897">023 67 67 897</a><a href="#book" className="rounded-full bg-[#b88a35] px-5 py-3 text-xs font-bold text-white">Book Appointment</a></div></div></header>
<section className="overflow-hidden bg-[linear-gradient(110deg,#f8fbfd_0%,#eef8fb_52%,#fff_100%)]"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><div className="flex items-center px-6 py-16 lg:px-10 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0a9aae]">Cosmetic, Implant & Family Dental Care</p><h1 className="mt-5 font-display text-6xl leading-[.98] tracking-[-.03em] md:text-7xl">Smile Bright.<br/>Feel Right.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#43556d]">Experience concierge-level dental care designed around your comfort, confidence and smile.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#book" className="inline-flex items-center gap-2 rounded-full bg-[#c0923c] px-6 py-4 font-bold text-white"><CalendarDays className="size-5"/>Book Appointment</a><a href="tel:+855236767897" className="inline-flex items-center gap-2 rounded-full border border-[#0b2347] px-6 py-4 font-bold"><Phone className="size-5"/>Call LaBelle Dental</a></div><div className="mt-7 flex flex-wrap gap-5 text-xs text-[#52647a]"><span>✓ New patients welcome</span><span>✓ Multilingual team</span><span>✓ Convenient location</span></div></div></div><div className="relative min-h-[520px]"><img src={hero} alt="Smiling Asian woman" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-y-0 left-0 w-24 bg-gradient-to-r from-[#eef8fb] to-transparent"/></div></div></section>
<section id="services" className="mx-auto -mt-5 grid max-w-6xl relative z-10 grid-cols-2 overflow-hidden rounded-2xl border bg-white shadow-lg md:grid-cols-6">{services.map((s,i)=><div key={s} className="border-r border-[#e6edf2] p-5 text-center"><div className="text-2xl text-[#0aa1b6]">{["✧","◉","♡","⌁","✦","+"][i]}</div><h3 className="mt-2 text-xs font-bold">{s}</h3></div>)}</section>
<section id="care" className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0a9aae]">Welcome to LaBelle Dental</p><h2 className="mt-3 font-display text-4xl">More Than a Dental Visit.<br/><i>A Better Dental Experience.</i></h2><p className="mt-6 max-w-xl leading-7 text-[#53657e]">We combine advanced technology, gentle techniques and personalized care to create a comfortable experience from the first question through your visit.</p><div className="mt-6 grid gap-3 text-sm"><span>✓ Gentle, comfortable care</span><span>✓ Modern dental technology</span><span>✓ Experienced, caring team</span><span>✓ Personalized treatment plans</span></div></div><div id="reviews" className="rounded-3xl bg-[#f2f7f8] p-10 text-center"><Star className="mx-auto size-8 fill-[#c0923c] text-[#c0923c]"/><blockquote className="mt-5 font-display text-3xl">“A dental experience built around the patient.”</blockquote><p className="mt-5 text-sm text-[#617086]">Comfort, clarity and personal attention at every step.</p></div></section>
<section className="bg-[#f4fbfc] px-6 py-14"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{[[Sparkles,"Advanced Technology","Modern tools supporting precise, comfortable care."],[HeartHandshake,"Personalized Care","Treatment conversations centered on your needs."],[ShieldCheck,"Comfort & Confidence","Clear answers before, during and after your visit."]].map(([I,t,d]:any)=><article key={t} className="rounded-2xl bg-white p-7 shadow-sm"><I className="size-8 text-[#0a9aae]"/><h3 className="mt-4 font-display text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#617086]">{d}</p></article>)}</div></section>
<section id="book" className="bg-[#dff7fa] px-6 py-12"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 md:flex-row"><div><p className="font-display text-3xl italic">Ready for a Brighter, Healthier Smile?</p><p className="mt-2 text-sm text-[#52647a]">We’d love to welcome you to LaBelle Dental.</p></div><div className="flex gap-3"><a className="rounded-full bg-[#c0923c] px-6 py-3 font-bold text-white" href="#">Book Appointment</a><a className="rounded-full border border-[#0b2347] px-6 py-3 font-bold" href="tel:+855236767897">Call 023 67 67 897</a></div></div></section>
<section className="fixed bottom-5 left-5 z-40 hidden w-64 rounded-2xl bg-[#0b2347] p-4 text-white shadow-xl md:block"><div className="flex items-center gap-2 font-bold"><MessageCircle className="size-5 text-[#39c3d3]"/>Ask LaBelle Dental</div><p className="mt-2 text-xs leading-5 text-[#d7e2ee]">Get instant answers and help preparing an appointment request.</p><a href="/#ask-labelle" className="mt-3 flex items-center justify-between rounded-lg bg-[#16aabd] px-3 py-2 text-xs font-bold">Chat with our AI Front Desk <ArrowRight className="size-4"/></a></section>
<footer id="contact" className="bg-[#071f43] px-6 py-10 text-white"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-3"><Brand/><div className="text-sm leading-7">#77 Street 110, Wat Phnom<br/>Daun Penh, Phnom Penh<br/>023 67 67 897</div><div className="text-sm leading-7">Mon–Sat · Contact clinic for hours<br/>Appointments confirmed by the clinic</div></div></footer>
</main>}
