import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Bot, CalendarDays, Globe2, Search, Sparkles } from "lucide-react";

export const Route = createFileRoute("/for-dentists")({ head: () => ({ meta: [{ title: "Dental AI Sales Platform" }, { name: "description", content: "Websites, AI front desks, booking and growth services for dental practices." }] }), component: DentistSales });

const replies = {
  website: "We create a clinic-specific website using your branding, services, doctors, location and approved patient information. It is designed for mobile visitors and built to turn visits into calls, questions and appointment requests.",
  chatbot: "Your AI front desk can answer approved clinic questions, qualify new patients, ask about symptoms and previous work, collect leads and hand conversations to your team instead of guessing.",
  booking: "Start with appointment requests, then connect live availability through Cal.com for booking, rescheduling, cancellation and reminders.",
  growth: "Optional growth services include local promotions, dental lead generation, SEO and content structured for search and AI answer tools.",
  more: "The core service combines a personalized dental website, AI chatbot and appointment booking, with human setup and support. Tell us your clinic name and what you want to improve first.",
};

function DentistSales() {
  const [answer,setAnswer]=useState("You are experiencing the type of digital front desk we can build for your practice. Choose a service or ask me to tell you more.");
  return <main className="min-h-screen bg-[#f7f4ed] text-[#123f3b]">
    <header className="border-b border-[#d7e7df] bg-white"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Link to="/" className="font-bold">View LaBelle patient site</Link><Link to="/for-dentists/telegram" className="rounded-full bg-[#1686d9] px-5 py-3 text-sm font-semibold text-white">Telegram handoff demo</Link></div></header>
    <section className="mx-auto grid min-h-[620px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#1686d9]">Built for dental practices</p><h1 className="mt-5 text-6xl font-semibold leading-[.92] tracking-[-.055em] sm:text-8xl">Your website becomes your best front desk.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#607772]">Personalized dental websites, patient chat, booking and growth tools—supported by real people.</p><div className="mt-9 grid gap-4 sm:grid-cols-2"><span className="flex gap-3"><Globe2 className="text-[#1686d9]"/> Clinic-specific website</span><span className="flex gap-3"><Bot className="text-[#1686d9]"/> AI patient support</span><span className="flex gap-3"><CalendarDays className="text-[#1686d9]"/> Online booking</span><span className="flex gap-3"><Search className="text-[#1686d9]"/> Leads & SEO</span></div></div>
      <div className="relative rounded-[2rem] bg-[#103d6a] p-4 shadow-2xl"><div className="sales-nudge absolute -right-2 -top-28 w-64 rounded-2xl bg-white p-4 shadow-xl"><small className="font-bold uppercase tracking-wider text-[#1686d9]">Ask the demo</small><div className="sales-nudge-words mt-2 h-7 overflow-hidden text-lg font-semibold"><span>Need a website?</span><span>Need a chatbot?</span><span>Need online booking?</span><span>Need more patients?</span></div></div><div className="rounded-3xl bg-white p-6"><div className="flex items-center gap-3 border-b pb-5"><span className="grid size-11 place-items-center rounded-full bg-[#1686d9] text-white"><Sparkles className="size-5"/></span><div><strong>Dental practice demo</strong><small className="block text-[#607772]">Ask how it works</small></div></div><div className="mt-6 min-h-40 rounded-2xl rounded-tl-sm bg-[#eef5f1] p-4 text-sm leading-6">{answer}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>setAnswer(replies.website)} className="rounded-full border px-3 py-2 text-xs">Website</button><button onClick={()=>setAnswer(replies.chatbot)} className="rounded-full border px-3 py-2 text-xs">AI chatbot</button><button onClick={()=>setAnswer(replies.booking)} className="rounded-full border px-3 py-2 text-xs">Booking</button><button onClick={()=>setAnswer(replies.growth)} className="rounded-full border px-3 py-2 text-xs">Leads & SEO</button><button onClick={()=>setAnswer(replies.more)} className="rounded-full bg-[#1686d9] px-3 py-2 text-xs text-white">Tell me more</button></div><button onClick={()=>setAnswer("Tell us your clinic name, current website or Facebook page, preferred contact method and which service you want to improve first. This will connect to the CRM in the production version.")} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-[#123f3b] px-5 py-3.5 font-semibold text-white">Create a demo for my clinic <ArrowRight className="size-4"/></button></div></div>
    </section>
    <section className="bg-white px-5 py-20"><div className="mx-auto max-w-5xl"><h2 className="text-4xl font-semibold tracking-[-.04em]">One platform from first contact to live client.</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{["Research dentist","Create clinic demo","Follow up in CRM","Launch & support"].map((x,i)=><div key={x} className="border-t border-[#1686d9] pt-4"><small>0{i+1}</small><h3 className="mt-2 font-semibold">{x}</h3></div>)}</div></div></section>
  </main>;
}