import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CalendarDays, MessageCircle, Phone, ArrowRight, X, Send, Star, Stethoscope, Sparkles, MapPin, Home, HeartPulse } from "lucide-react";
import { answerDentalQuestion } from "../lib/dentalChatbot";
import { KrispyWidget } from "../components/KrispyWidget";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "LaBelle Dental Clinic | Phnom Penh" },
    { name: "description", content: "Patient information, dental services and appointment requests for LaBelle Dental Clinic in Phnom Penh." },
  ] }),
  component: PatientSite,
});

const services = [
  ["Checkups & cleaning", "Routine examinations, scaling, polishing and preventive care."],
  ["Orthodontics", "Braces consultations and treatment for tooth alignment."],
  ["Dental implants", "Implant consultations, records review and treatment planning."],
  ["Fillings & repairs", "Assessment of cavities, chips, broken teeth and existing fillings."],
  ["Crowns & root-canal care", "Consultations for crowns, posts and root-canal treatment."],
  ["Cosmetic consultations", "Questions about veneers and smile-improvement options."],
];

function PatientSite() {
  const [chatOpen, setChatOpen] = useState(false);
  const [answer, setAnswer] = useState("សួស្តី! Hi, I’m LaBelle Front Desk. How can I help with your dental visit?");
  const [question, setQuestion] = useState("");
  const [requested, setRequested] = useState(false);

  function ask(nextQuestion = question) {
    if (!nextQuestion.trim()) return;
    const result = answerDentalQuestion(nextQuestion);
    setAnswer(result.answer);
    setQuestion("");
  }

  return <main className="min-h-screen bg-[#f7f9ff] pb-20 text-[#181c20] md:pb-0">
    <header className="sticky top-0 z-30 border-b border-[#dfe5ec] bg-white/95 backdrop-blur">
      <div className="mx-auto flex h-16 max-w-[1200px] items-center justify-between px-4 md:px-8">
        <a href="/" className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-full bg-[#006098] text-white"><HeartPulse className="size-5"/></span><strong className="font-display text-xl text-[#006098]">LaBelle Dental</strong></a>
        <nav className="hidden items-center gap-6 text-sm font-semibold text-[#404851] md:flex"><a className="text-[#006098]" href="#top">Home</a><a href="#services">Services</a><a href="#appointments">Booking</a><a href="#front-desk">Support</a></nav>
        <a href="tel:+855236767897" className="hidden rounded-lg bg-[#006098] px-4 py-2.5 text-sm font-semibold text-white sm:inline-flex">Call clinic</a>
      </div>
    </header>

    <section id="top" className="mx-auto grid max-w-[1200px] gap-8 px-4 py-12 md:grid-cols-2 md:px-8 md:py-20">
      <div className="self-center"><p className="mb-4 text-sm font-semibold uppercase tracking-[.18em] text-[#006098]">Serving Phnom Penh</p><h1 className="font-display text-5xl font-bold leading-[1.02] tracking-[-.035em] sm:text-6xl">Healthy smiles.<br/><span className="italic text-[#006098]">Warm welcome.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-[#404851]">Trusted dental care in Daun Penh, with a multilingual front desk ready to help patients quickly.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#appointments" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#006098] px-6 py-3.5 font-semibold text-white shadow-sm"><CalendarDays className="size-5"/> Request appointment</a><button onClick={() => setChatOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-[#006098] bg-white px-6 py-3.5 font-semibold text-[#006098]"><MessageCircle className="size-5"/> Ask LaBelle</button></div></div>
      <div className="overflow-hidden rounded-xl border border-[#dfe5ec] bg-white shadow-[0_8px_30px_rgba(41,72,107,.08)]"><img src="https://harbor-dental-ai-front-desk.blond-titan-1971.chatgpt.site/harbor-dental-hero.png" alt="Dentist speaking with a patient" className="h-[420px] w-full object-cover md:h-[520px]" /></div>
    </section>

    <section id="services" className="mx-auto max-w-[1200px] px-4 py-16 md:px-8 md:py-24"><div className="mb-10 max-w-2xl"><h2 className="font-display text-4xl font-bold tracking-[-.03em]">Dental care starts with the right questions.</h2><p className="mt-4 leading-7 text-[#404851]">Ask about treatment, previous dental work or records. LaBelle’s team confirms availability, suitability and pricing.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([title,text],i)=><article key={title} className={`flex min-h-56 flex-col rounded-xl border border-[#e1e8ed] p-7 shadow-[0_4px_24px_rgba(41,72,107,.05)] ${i===5?"bg-[#007abe] text-white":"bg-white"}`}><span className={`mb-5 grid size-12 place-items-center rounded-full ${i===5?"bg-white text-[#007abe]":"bg-[#f4f9fc] text-[#006098]"}`}>{i===5?<Sparkles className="size-5"/>:<Stethoscope className="size-5"/>}</span><h3 className="font-display text-2xl font-semibold">{title}</h3><p className={`mt-3 text-sm leading-6 ${i===5?"text-white/85":"text-[#5d6670]"}`}>{text}</p><span className={`mt-auto pt-6 text-sm font-semibold ${i===5?"text-white":"text-[#006098]"}`}>Learn more →</span></article>)}</div></section>

    <section id="reviews" className="bg-white px-4 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#006098]">Patient reviews</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.03em]">Care people recommend.</h2><div className="mt-6 flex items-center gap-4"><strong className="font-display text-5xl">4.5</strong><div><div className="flex text-[#f6a84b]">{[1,2,3,4,5].map(n=><Star key={n} className="size-5 fill-current"/>)}</div><p className="mt-1 text-sm text-[#5d6670]">50+ publicly listed reviews</p></div></div><p className="mt-8 max-w-sm text-xs leading-5 text-[#707882]">Public review information is independently sourced and should be confirmed by LaBelle before production launch.</p></div><div className="grid gap-5 sm:grid-cols-2"><ReviewCard text="“Good dental services” from a patient who reports visiting LaBelle for about 15 years." source="Long-term patient · Cambodia Expats Online" href="https://cambodiaexpatsonline.com/ask-the-expats-questions-answers/reasonably-priced-dentist-t60056-10.html"/><ReviewCard text="A recent recommendation describes LaBelle as good quality, friendly and more affordable than premium alternatives." source="Phnom Penh patient recommendation · Reddit" href="https://www.reddit.com/r/cambodia/comments/1vlprtx/dentist_recommendation_and_price/"/></div></div></section>

    <section id="appointments" className="mx-auto grid max-w-[1200px] gap-10 px-4 py-16 md:px-8 md:py-24 lg:grid-cols-2"><div className="lg:sticky lg:top-28 lg:self-start"><h2 className="font-display text-4xl font-bold tracking-[-.03em] text-[#006098]">Request a preferred visit time.</h2><p className="mt-5 text-lg leading-8 text-[#404851]">No login is required. LaBelle confirms every appointment by phone to make sure the visit is scheduled correctly.</p><img src="https://harbor-dental-ai-front-desk.blond-titan-1971.chatgpt.site/labelle-clinic.jpg" alt="LaBelle Dental Clinic" className="mt-8 hidden h-64 w-full rounded-xl object-cover shadow-sm lg:block"/></div><form onSubmit={(e)=>{e.preventDefault();setRequested(true)}} className="rounded-2xl border border-[#e1e8ed] bg-white p-6 shadow-[0_4px_30px_rgba(41,72,107,.08)] md:p-8"><label className="grid gap-2 text-sm font-semibold">Service<select className="h-12 rounded-lg border bg-[#f7f9ff] px-3"><option>Checkup & cleaning</option><option>Orthodontics consultation</option><option>Dental implant consultation</option><option>Tooth pain or broken tooth</option></select></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Preferred date<input required type="date" className="h-12 rounded-lg border bg-[#f7f9ff] px-3"/></label><label className="grid gap-2 text-sm font-semibold">Preferred time<select className="h-12 rounded-lg border bg-[#f7f9ff] px-3"><option>8:30 AM</option><option>10:00 AM</option><option>2:00 PM</option><option>5:00 PM</option></select></label></div><label className="mt-5 grid gap-2 text-sm font-semibold">Name<input required className="h-12 rounded-lg border bg-[#f7f9ff] px-3" placeholder="Your full name"/></label><label className="mt-5 grid gap-2 text-sm font-semibold">Phone or Telegram<input required className="h-12 rounded-lg border bg-[#f7f9ff] px-3" placeholder="Phone number or username"/></label><button className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#006098] px-5 py-4 font-semibold text-white">Request this time <ArrowRight className="size-4"/></button><p className="mt-3 text-center text-xs text-[#5d6670]">The clinic will call to confirm availability.</p>{requested&&<p className="mt-4 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-900">Your demo request is prepared. LaBelle would call to confirm; no real appointment was created.</p>}</form></section>

    <section id="front-desk" className="bg-[#eef4f8] px-4 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#006098]">AI front desk</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.03em]">Ask LaBelle before your visit.</h2><p className="mt-5 text-lg leading-8 text-[#404851]">The front desk answers approved questions, asks about previous treatment and helps prepare a useful appointment request without diagnosing.</p></div><div className="rounded-2xl border border-[#dfe5ec] bg-white p-6 shadow-sm"><div className="rounded-xl bg-[#f4f9fc] p-4 text-sm leading-6">{answer}</div><div className="mt-5 flex flex-wrap gap-2">{["What services do you offer?","I have X-rays","I have tooth pain","Book an appointment"].map(x=><button key={x} onClick={()=>ask(x)} className="rounded-full border px-3 py-2 text-xs text-[#006098]">{x}</button>)}</div><form onSubmit={(e)=>{e.preventDefault();ask()}} className="mt-5 flex rounded-lg border bg-white p-1.5"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask LaBelle…" className="min-w-0 flex-1 bg-transparent px-3 outline-none"/><button aria-label="Send" className="grid size-10 place-items-center rounded-lg bg-[#006098] text-white"><Send className="size-4"/></button></form></div></div></section>

    <section id="about" className="mx-auto grid max-w-[1200px] gap-10 px-4 py-16 md:px-8 md:py-24 lg:grid-cols-2"><div className="overflow-hidden rounded-xl"><img src="https://harbor-dental-ai-front-desk.blond-titan-1971.chatgpt.site/labelle-clinic.jpg" alt="LaBelle Dental Clinic storefront" className="h-[380px] w-full object-cover"/></div><div className="self-center"><MapPin className="size-8 text-[#006098]"/><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.03em]">Dental care in the heart of Phnom Penh.</h2><p className="mt-5 text-lg leading-8 text-[#404851]">#77 Street 110, Sangkat Wat Phnom, Khan Daun Penh, Phnom Penh</p><p className="mt-4 font-semibold">092 96 31 94 · 023 67 67 897</p><p className="mt-6 text-xs text-[#707882]">Public information requires clinic verification before production use.</p></div></section>

    <footer className="border-t border-[#dfe5ec] bg-white px-4 py-10 text-center text-sm text-[#5d6670]">LaBelle Dental Clinic · #77 Street 110, Phnom Penh</footer>

    <nav className="fixed bottom-0 left-0 z-40 flex w-full items-center justify-around border-t border-[#dfe5ec] bg-white px-2 pb-3 pt-2 shadow-[0_-4px_20px_rgba(66,96,132,.08)] md:hidden"><a href="#top" className="flex flex-col items-center gap-1 text-[10px] font-semibold text-[#006098]"><Home className="size-5"/>Home</a><a href="#services" className="flex flex-col items-center gap-1 text-[10px] font-semibold text-[#5d6670]"><Stethoscope className="size-5"/>Services</a><a href="#appointments" className="flex flex-col items-center gap-1 rounded-full bg-[#007abe] px-4 py-1 text-[10px] font-semibold text-white"><CalendarDays className="size-5"/>Booking</a><button onClick={()=>setChatOpen(true)} className="flex flex-col items-center gap-1 text-[10px] font-semibold text-[#5d6670]"><MessageCircle className="size-5"/>Support</button></nav>

    <button onClick={()=>setChatOpen(true)} className="fixed bottom-5 right-5 z-40 hidden items-center gap-2 rounded-full bg-[#006098] px-5 py-3.5 font-semibold text-white shadow-xl md:flex"><MessageCircle className="size-5"/> Ask LaBelle</button>
    <KrispyWidget />
    {chatOpen&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/30 p-4 sm:place-items-center"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><small className="font-semibold uppercase tracking-[.14em] text-[#006098]">LaBelle Front Desk</small><h2 className="mt-1 font-display text-2xl font-bold">How can we help?</h2></div><button onClick={()=>setChatOpen(false)} aria-label="Close" className="grid size-9 place-items-center rounded-full border"><X className="size-4"/></button></div><div className="mt-6 grid gap-3"><a href="#appointments" onClick={()=>setChatOpen(false)} className="rounded-xl border p-4 font-semibold">Choose an appointment time</a><a href="#front-desk" onClick={()=>setChatOpen(false)} className="rounded-xl border p-4 font-semibold">Ask a clinic question</a><a href="tel:+855236767897" className="flex items-center gap-2 rounded-xl border p-4 font-semibold"><Phone className="size-5"/> Call LaBelle Dental Clinic</a></div></div></div>}
  </main>;
}

function ReviewCard({text,source,href}:{text:string;source:string;href:string}){return <article className="rounded-xl border border-[#e1e8ed] bg-[#f7f9ff] p-6"><div className="flex text-[#f6a84b]">{[1,2,3,4,5].map(n=><Star key={n} className="size-4 fill-current"/>)}</div><blockquote className="mt-5 leading-7">{text}</blockquote><p className="mt-5 text-sm font-semibold">{source}</p><a href={href} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-[#006098]">Read source →</a></article>}
