/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForDentistsRouteImport } from './routes/for-dentists'
import { Route as ForDentistsTelegramRouteImport } from './routes/for-dentists.telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDentistsRoute = ForDentistsRouteImport.update({
  id: '/for-dentists',
  path: '/for-dentists',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDentistsTelegramRoute = ForDentistsTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => ForDentistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/for-dentists': typeof ForDentistsRouteWithChildren
  '/for-dentists/telegram': typeof ForDentistsTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/for-dentists': typeof ForDentistsRouteWithChildren
  '/for-dentists/telegram': typeof ForDentistsTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/for-dentists': typeof ForDentistsRouteWithChildren
  '/for-dentists/telegram': typeof ForDentistsTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/for-dentists' | '/for-dentists/telegram'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/for-dentists' | '/for-dentists/telegram'
  id: '__root__' | '/' | '/admin' | '/for-dentists' | '/for-dentists/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ForDentistsRoute: typeof ForDentistsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-dentists': {
      id: '/for-dentists'
      path: '/for-dentists'
      fullPath: '/for-dentists'
      preLoaderRoute: typeof ForDentistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-dentists/telegram': {
      id: '/for-dentists/telegram'
      path: '/telegram'
      fullPath: '/for-dentists/telegram'
      preLoaderRoute: typeof ForDentistsTelegramRouteImport
      parentRoute: typeof ForDentistsRoute
    }
  }
}

interface ForDentistsRouteChildren {
  ForDentistsTelegramRoute: typeof ForDentistsTelegramRoute
}

const ForDentistsRouteChildren: ForDentistsRouteChildren = {
  ForDentistsTelegramRoute: ForDentistsTelegramRoute,
}

const ForDentistsRouteWithChildren = ForDentistsRoute._addFileChildren(
  ForDentistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ForDentistsRoute: ForDentistsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
